### ISSUE TITLE
Idea: add a guide on how to choose an PDE solution approach (maybe with plots)

### ISSUE THREAD

**Issue by juripfammatter** [MeierTobias/eth-analysis-3#43]
![image](https://github.com/MeierTobias/eth-analysis-3/assets/119895438/9e9eb273-aa77-4f81-8a3d-ca9fb9ed5877)

**Comment by MeierTobias** [comment]
Very good idea, maybe we can combine it with a flowchart if that helps.
[latex example](https://tex.stackexchange.com/a/175979)

**Comment by MeierTobias** [comment]
Nice graphic, I like the color scheme 😉

**Comment by MeierTobias** [comment]
I think this is done with #51. Should we close this issue?
