### ISSUE TITLE
Appendix progress

### ISSUE THREAD

**Issue by MeierTobias** [MeierTobias/eth-analysis-3#56]
![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/198da2cc-cd3f-4cfa-a5e0-0702d2e3faac)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/9f7fae39-5efa-46e9-bbf7-fb924aa72faa)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/95c3a64c-a280-40e0-8ab6-62ea2b55feeb)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/3a6c5ef2-2cd5-4d33-90c1-cdc4beba7e85)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/d52e1374-a493-4a89-8908-56aee7a53ad5)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/2557faef-27fe-4325-ad7a-389e196d6228)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/f897c414-1cd9-4519-baf0-0cd132b5d0dd)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/d51fa63b-aac9-48d3-a342-57197ccf629e)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/3e8a8a25-d210-46be-8394-c7dbefd6c3cb)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/202e50f8-ad7f-4d4b-b7f7-d23518f2aaa4)

![image](https://github.com/MeierTobias/eth-analysis-3/assets/30720836/bfdc6ebe-215b-4a76-b990-6fcc4ff7b80c)

**Comment by juripfammatter** [comment]
can this be closed?

**Comment by MeierTobias** [comment]
Yes :)
